config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'pages#home'

  resources :wishlists, only: [:new, :create, :show, :edit, :update] do
    post 'wishlist_items/:id', to: 'purchases#create', as: 'item_purchase'
    delete 'wishlist_items/:id', to: 'purchases#destroy', as: 'item_cancel_purchase'
  end
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :owner, class_name: 'User', foreign_key: 'user_id', dependent: :destroy
  has_many   :wishlist_items, dependent: :destroy
  has_many   :wishlist_invitees, dependent: :destroy
  has_many   :invitees, through: :wishlist_invitees, source: :user

  accepts_nested_attributes_for :owner
  accepts_nested_attributes_for :wishlist_items,
                                :invitees,
                                reject_if: :all_blank

  validates :title,
            :invitees,
            :wishlist_items,
            presence: true

  validate  :ensure_all_email_addresses_are_unique, unless: -> { owner.nil? }
  validate  :ensure_gmail_addresses_are_unique, unless: -> { owner.nil? }

  EMAIL_RE = Regexp.new(/(?<before_plus>.+)\+(?<after_plus>.+)@(?<domain>.+)/)

  def participants_email_addresses
    # Interestingly, `invitees.pluck` and `invitees.select` both return empty arrays.
    # TODO: Look further into this
    email_addresses = [owner.email] + invitees.map(&:email)
    email_addresses.compact
  end

  private

  def ensure_all_email_addresses_are_unique
    downcased_addresses = participants_email_addresses.map(&:downcase)
    add_error_if_not_unique(downcased_addresses)
  end

  def ensure_gmail_addresses_are_unique
    gmail_addresses = find_gmail_users
    gmail_addresses.compact
    stripped_addresses = strip_addresses(gmail_addresses)

    add_error_if_not_unique(stripped_addresses)
  end

  def add_error_if_not_unique(addresses)
    errors.add(:wishlist, 'email addresses must be unique.') if addresses.length != addresses.uniq.length
  end

  def find_gmail_users
    participants_email_addresses.filter { |address| address.include?('gmail.com') }
  end

  def strip_addresses(addresses)
    stripped_addresses = []
    addresses.each do |address|
      address = strip_periods(address)
      address = strip_part_after_plus_sign(address) if address.include?('+')
      stripped_addresses << address
    end
    stripped_addresses
  end

  def strip_periods(address)
    address.downcase.gsub('.', '')
  end

  def strip_part_after_plus_sign(address)
    matches = address.match(EMAIL_RE)
    address = "#{matches[:before_plus]}@#{matches[:domain]}"
  end
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :set_wishlist, only: %i[show edit update]
  before_action :ensure_wishlist, except: %i[new create]
  before_action :set_user, only: %i[show edit update]
  before_action :authenticate_user, only: [:show]
  before_action :authenticate_owner, only: %i[edit update]

  def new
    @wishlist = Wishlist.new
    @wishlist.build_owner
    @wishlist.wishlist_items.build
    @wishlist.invitees.build
  end

  def create
    @wishlist = Wishlist.new(wishlist_params)
    if @wishlist.save
      SendEmails.new(owner: @wishlist.owner, invitees: @wishlist.invitees).call
      redirect_to(wishlist_path(@wishlist, user_id: @wishlist.owner.id), notice: 'Wishlist created!')
    else
      respond_to do |format|
        failure_message = 'Your wishlist could not be created...'
        format.js { flash.now[:alert] = failure_message }
        # TODO: Fix this (format.html doesn't work)
        format.html do
          flash.now[:alert] = failure_message
          render :new
        end
      end
    end
  end

  def show; end

  def edit; end

  def update
    # TODO: This method is quite big. Refactor into something smaller
    original_items_count = @wishlist.wishlist_items.count
    original_invitees = @wishlist.invitees.to_a

    if @wishlist.update(wishlist_params)
      if original_items_count != @wishlist.wishlist_items.count
        send_wishlist_updated_emails(owner: nil, invitees: @wishlist.invitees)
      end

      new_invitees = @wishlist.invitees.to_a.filter do |invitee|
        !original_invitees.include? invitee
      end

      SendEmails.new(owner: nil, invitees: new_invitees).call
      send_wishlist_updated_emails(invitees: nil)

      redirect_to(
        wishlist_path(@wishlist, user_id: @wishlist.owner.id),
        notice: 'Wishlist updated!'
      )
    else
      respond_to do |format|
        failure_message = 'Your wishlist could not be updated...'
        format.js { flash.now[:alert] = failure_message }
        # TODO: Fix this (format.html doesn't work)
        format.html do
          flash.now[:alert] = failure_message
          render :new
        end
      end
    end
  end

  private

  def wishlist_params
    params.require(:wishlist).permit(
      :id,
      :title,
      owner_attributes: %i[
        id
        email
      ],
      wishlist_items_attributes: %i[
        id
        name
        url
      ],
      invitees_attributes: %i[
        id
        email
      ]
    )
  end

  def redirect_to_root
    redirect_to root_path, alert: 'The wishlist you are trying to access ' \
                                  'does not exist or you do not have ' \
                                  'access to it.'
  end

  def set_wishlist
    @wishlist = Wishlist.find_by(id: params[:id])
  end

  def set_user
    @user = User.find_by(id: params[:user_id])
  end

  def ensure_wishlist
    redirect_to_root if @wishlist.nil?
  end

  def authenticate_user
    redirect_to_root if
      !@wishlist.invitees.include?(@user) && @wishlist.owner != @user
  end

  def authenticate_owner
    redirect_to_root if @wishlist.owner != @user
  end

  def send_wishlist_updated_emails(invitees:, owner: @wishlist.owner)
    if owner
      WishlistMailer.with(wishlist_id: @wishlist.id, recipient_id: owner.id)
                    .own_wishlist_updated.deliver_later
    end

    if invitees
      invitees.each do |invitee|
        WishlistMailer.with(wishlist_id: @wishlist.id, recipient_id: invitee.id)
                      .wishlist_updated.deliver_later
      end
    end
  end
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/wishlists/_cancel_purchase.html.erb
<%= link_to 'Cancel purchase',
    wishlist_item_cancel_purchase_path(wishlist, wishlist_item, user_id: user_id),
    data: {
      turbo_frame: dom_id(wishlist_item),
      turbo_confirm: 'Cancel purchase?',
      turbo_method: :delete
    }
%>

app/views/wishlists/_purchase.html.erb
<%= link_to 'Purchase',
    wishlist_item_purchase_path(wishlist, wishlist_item, user_id: user_id),
    data: {
      turbo_confirm: 'Purchase item?',
      turbo_method: :post
    }
%>

app/views/wishlists/_purchased_item.html.erb
<div>
  <li class="wishlist-item__name--purchased">
    <% if wishlist_item.url.blank? %> 
      <%= wishlist_item.name %>
    <% else %> 
      <%= link_to wishlist_item.name, wishlist_item.url, style: 'color: black' %> 
    <% end %>
  </li>
</div>
<div>
  <% if purchased_by_current_user %>
    <%= link_to 'Cancel purchase',
                wishlist_item_cancel_purchase_path(wishlist, wishlist_item, user_id: user.id),
                class: "wishlist-item__purchase-button",
                data: {
                  turbo_confirm: 'Cancel purchase?',
                  turbo_method: :delete
                }
    %> 
  <% end %> 
</div>
<div>
  <% if !purchased_by_current_user %> 
    Purchased by <%= wishlist_item.purchase.user.email %>  
    on <%= wishlist_item.purchase.created_at.strftime("%A, %B %e") %> 
  <% end %> 
</div>

app/views/wishlists/_unpurchased_item.html.erb
<div>
  <li>
    <% if wishlist_item.url.blank? %> 
      <%= wishlist_item.name %> 
    <% else %> 
      <%= link_to wishlist_item.name, wishlist_item.url %> 
    <% end %> 
  </li>
</div>
<div>
  <%= link_to 'Purchase',
    wishlist_item_purchase_path(wishlist, wishlist_item, user_id: user.id),
    class: "wishlist-item__purchase-button",
    data: {
      turbo_method: :post
      }
  %> 
</div>

app/views/wishlists/_wishlist_item.html.erb
<%= turbo_frame_tag wishlist_item, class: "wishlist-item" do %>
  <div>
    <li>
      <% if wishlist_item.url.blank? %>
        <%= wishlist_item.name %>
      <% else %>
        <%= link_to wishlist_item.name, wishlist_item.url %>
      <% end %>
    </li>
  </div>
  <div>
    <% if !wishlist_item.purchased? %>
      <%= link_to 'Purchase',
          wishlist_item_purchase_path(wishlist, wishlist_item, user_id: user.id),
          class: "wishlist-item__purchase-button",
          data: {
            turbo_confirm: 'Purchase item?',
            turbo_method: :post
          }
      %>
    <% end %>

    <% if wishlist_item.purchased? && wishlist_item.purchase.user == user %>
      <%= link_to 'Cancel purchase',
                  wishlist_item_cancel_purchase_path(wishlist, wishlist_item, user_id: user.id),
                  class: "wishlist-item__purchase-button",
                  data: {
                    turbo_confirm: 'Cancel purchase?',
                    turbo_method: :delete
                  }
      %>
    <% end %>
  </div>
  <div>
    <% if wishlist_item.purchased? && wishlist_item.purchase.user != user %>
      Purchased by <%= wishlist_item.purchase.user.email %> on <%= wishlist_item.purchase.created_at.strftime("%A, %B %e") %>
    <% end %>
  </div>
<% end %>

app/views/wishlists/_wishlist_item_fields.html.erb
<div class="nested-fields">
  <div class="field mb-4 w-64">
    <%= f.hidden_field :_destroy %>
    <%= f.label :name, class: 'form-label' %>
    <%= f.text_field :name, class: 'form-input' %>
    <small>
      <%= link_to "Remove item", "#", data: { action: "click->nested-form#remove_association" } %>
    </small>
  </div>
</div>

app/views/wishlists/edit.html.erb
<div id="errors-container"></div>

<div class="section">
  <h1>Edit your wishlist</h1>

  <%= form_with model: @wishlist, data: { controller: 'wishlist' } do |f| %>
    <%= hidden_field_tag "user_id", "#{@current_user.id}" %>
    <div class="wishlist-content">
      <div>
        <%= f.label :title, 'Wishlist Title:' %>
        <%= f.text_field :title, disabled: true %>
      </div>

      <div>
        <%= f.fields_for :owner do |owner_form| %>
          <%= owner_form.label :email, 'Your email:' %>
          <%= owner_form.email_field :email, disabled: true %>
        <% end %>
      </div>

      <label>Wishlist items:</label>
      <ul data-wishlist-target="itemList">
        <%= f.fields_for :wishlist_items do |wishlist_items_form| %>
          <li class='flex'>
            <%= wishlist_items_form.text_field :name, disabled: true %>
            <%= wishlist_items_form.text_field :url, disabled: true %>
          </li>
        <% end %>
      </ul>
      <%= button_tag '+', data: { action: 'click->wishlist#addItem' }, class: 'font-size-p-responsive button add-button' %>

      <template data-wishlist-target='itemTemplate'>
        <li class='flex'>
          <input type='text'>
          <input type='text'>
        </li>
      </template>
    </div>

    <div class="invitees-content">
      <h3>Invite some people</h3>
      <label>Emails:</label>
      <ul data-wishlist-target='inviteeList'>
        <%= f.fields_for :invitees do |invitees_form| %>
          <li>
            <%= invitees_form.email_field :email, disabled: true %>
          </li>
        <% end %>
      </ul>
      <%= button_tag '+', data: { action: 'click->wishlist#addInvitee' }, class: 'font-size-p-responsive button add-button' %>

      <template data-wishlist-target='inviteeTemplate'>
        <li>
          <input type='email' placeholder='my_friend@their_email.com'>
        </li>
      </template>
    </div>

    <%= f.submit 'Update wishlist', data: { 'disable-with': 'Updating...' }, class: 'button font-size-p-responsive submit-button' %>
  <% end %>
</div>

app/views/wishlists/new.html.erb
<div id="errors-container"></div>

<div class="section">
  <h1>Create your wishlist</h1>

  <%= form_with model: @wishlist, data: { controller: 'wishlist', turbo: false } do |f| %>
    <div class="wishlist-content">
      <div>
        <%= f.label :title, 'Wishlist Title:' %>
        <%= f.text_field :title, placeholder: 'My birthday wishlist' %>
        <% @wishlist.errors.messages_for(:title).each do |error_message| %>
          <div class='field_with_errors'>
            <%= error_message %>
          </div>
        <% end %>
      </div>

      <div>
        <%= f.fields_for :owner do |owner_form| %>
          <%= owner_form.label :email, 'Your email:' %>
          <%= owner_form.email_field :email, placeholder: 'me@my_email.com' %>
        <% end %>
        <% @wishlist.errors.messages_for(:'owner.email').each do |error_message| %>
          <div class='field_with_errors'>
            <%= error_message %>
          </div>
        <% end %>
      </div>

      <label>Wishlist items:</label>
      <ul data-wishlist-target="itemList">
        <%= f.fields_for :wishlist_items do |wishlist_items_form| %>
          <li class='flex'>
            <%= wishlist_items_form.text_field :name, placeholder: 'New bike' %>
            <%= wishlist_items_form.text_field :url, placeholder: 'https://www.new-bike.com' %>
          </li>
        <% end %>
      </ul>
      <%= button_tag '+', data: { action: 'click->wishlist#addItem' }, class: 'font-size-p-responsive button add-button' %>

      <template data-wishlist-target="itemTemplate">
        <li class='flex'>
          <input type='text'>
          <input type='text'>
        </li>
      </template>
    </div>

    <div class="invitees-content">
      <h3>Invite some people</h3>
      <ul data-wishlist-target="inviteeList">
        <%= f.fields_for :invitees do |invitees_form| %>
          <label>Email:</label>
          <li>
            <%= invitees_form.email_field :email, placeholder: 'my_friend@their_email.com' %>
          </li>
        <% end %>
      </ul>
      <%= button_tag '+', data: { action: 'click->wishlist#addInvitee' }, class: 'font-size-p-responsive button add-button' %>

      <template data-wishlist-target="inviteeTemplate">
        <li>
          <input type='email'>
        </li>
      </template>
    </div>

    <%= f.submit 'Create new wishlist', data: { 'disable-with': 'Creating...' }, class: 'button font-size-p-responsive submit-button' %>
  <% end %>
</div>

app/views/wishlists/show.html.erb
<div class="flash-container"></div>

<%= turbo_stream_from "purchase" %>

<% if @wishlist.owner == @user %>
  <%= link_to 'Edit wishlist', edit_wishlist_path(@wishlist, user_id: @user.id) %>
<% end %>

<div class="section">
  <h1><%= @wishlist.title %></h1>
  <div>
    <% @wishlist.wishlist_items.includes(purchase: [:user]).each do |wishlist_item| %>
      <% if @wishlist.owner == @user %>
        <div id="wishlist-item-<%= wishlist_item.id %>">
          <div>
            <li>
              <% if wishlist_item.url.blank? %>
                <%= wishlist_item.name %>
              <% else %>
                <%= link_to wishlist_item.name, wishlist_item.url %>
              <% end %>
            </li>
          </div>
        </div>
      <% else %>
        <%# TODO: Remove? %>
        <%# <%= render partial: 'wishlist_item', locals: { wishlist_item: wishlist_item, wishlist: @wishlist, user: @user, purchase: wishlist_item.reload.purchase } %>
 
        <%= turbo_frame_tag wishlist_item, class: "wishlist-item" do %> 
          <% if wishlist_item.purchased? %>
            <%= render partial: 'purchased_item', locals: { wishlist_item: wishlist_item, wishlist: @wishlist, user: @user, purchased_by_current_user: @user == wishlist_item.purchase.user } %>
          <% else %>
            <%= render partial: 'unpurchased_item', locals: { wishlist_item: wishlist_item, wishlist: @wishlist, user: @user } %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>